hostname: black-pearl
manage_etc_hosts: true

users:
  - name: {USER}
    gecos: "{GECOS}"
    sudo: ALL=(ALL) NOPASSWD:ALL
    home: {HOME}
    shell: /bin/bash
    groups: users,docker
    lock_passwd: true
    ssh-authorized-keys:
        - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDKvc90UsU2vPQ8E1qPwhxh6WLK5OyukQjuIp8dKvpCL+24A9mtaAQ2QRoA2VKFgWUSUO+IYHWBJnIW7f86kVNZn157lS5uhAJ+UMIS4HcoRAXRqFItrWHHvRLsLjVlJtQoxTEr4YE2Yw46ekbgoNlchOvzIMUG4nPRVLZE+u6aoVPNouAp0Bn8ENH2bFUAW1r34oENoU63zc1kfdFFebTr54YnJG24fZqJkYpJfTr6Q45wgnLmkLQPHBGDmHBPuVZcRTKskUl99cIelRjZXu9+w5LnNTQhbWBQE8QJEfIK42fV50zVwww9AHzQmSjAegF4efNc2MMvYrHLNCFNnSNd cornelius@manjaro-l540

package_upgrade: false
packages:
  - ca-certificates
  - curl
  - tmux
  - jq
  - vim

runcmd:
  - sed -i -e "s|#PasswordAuthentication yes|PasswordAuthentication no|g" /etc/ssh/sshd_config
  - systemctl restart sshd.service

  - sed -ie "s|Servers=.*||g" /etc/systemd/timesyncd.conf
  - echo "Servers={TIMESERVER}" | sudo tee -a /etc/systemd/timesyncd.conf
  - systemctl restart systemd-timesyncd.service

  - sed -e "s|ExecStart=/usr/bin/dockerd.*|ExecStart=/usr/bin/dockerd|g" /lib/systemd/system/docker.service | sudo tee /etc/systemd/system/docker.service
  - systemctl daemon-reload
  - systemctl restart docker.service

  - docker swarm join --token  {SWARM_TOKEN} {SWARM_LEADER_IP}

power_state:
  mode: reboot
  message: Bye Bye
  condition: True
  timeout: 1

write_files:
  - path: /etc/docker/daemon.json
    content: |
      {
        "storage-driver":"overlay2",
        "hosts":[
          "unix:///var/run/docker.sock"
        ]
      }
  - path: /etc/local_configuration.json
    content: |
      {
        "hostname": "/etc/hostname",
        "machine_id": "123456789",
        "building": "L9",
        "room": "Wohnzimmer"
      }
