#cloud-config
hostname: {HOSTNAME}
manage_etc_hosts: true

users:
  - name: {USER}
    gecos: "{GECOS}"
    sudo: ALL=(ALL) NOPASSWD:ALL
    home: {HOME}
    shell: /bin/bash
    groups: users,docker
    lock_passwd: true
    ssh-authorized-keys:
        - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDS/bzCrcU+Yoq4UrtJguhOyHi+zeNhRap17VghVGljXiyvvxyGiXtBb8Cg3LH0NFmptamc8Xqcw4B9qM/VqZX6ZYuKaB4l0fXmix5cL5NYUscd4hLwLWUN6JrsCmFFOhpAoq6s0GYiRF21fm8F+IItlQKsjGS7SwBdj14DoWsTbh1NEjgqqeSncOjBzwnjziVB/Pf8EK4eM7yPPR/xRFoaqVgI8qlnIzzrbLlJZuRXofQw8zm5BHewlzoTOdc8h7oYDWYUtadkEGyDpNZ37qEOjgxQYGK8VX3HzAZQSSa1ep9LavkGtMzmpTG9QS385tuH5P6F8ag+RDPNTLumUir9 cornelius@manjaro-t470

package_upgrade: false
packages:
  - ca-certificates
  - curl
  - tmux
  - jq
  - vim

runcmd:
  - sed -i -e "s|#PasswordAuthentication yes|PasswordAuthentication no|g" /etc/ssh/sshd_config
  - systemctl restart sshd.service

  - sed -ie "s|Servers=.*||g" /etc/systemd/timesyncd.conf
  - echo "Servers={TIMESERVER}" | sudo tee -a /etc/systemd/timesyncd.conf
  - systemctl restart systemd-timesyncd.service

  - sed -e "s|ExecStart=/usr/bin/dockerd.*|ExecStart=/usr/bin/dockerd|g" /lib/systemd/system/docker.service | sudo tee /etc/systemd/system/docker.service
  - systemctl daemon-reload
  - systemctl restart docker.service

  - docker swarm join --token  {SWARM_TOKEN} {SWARM_LEADER_IP}

power_state:
  mode: reboot
  message: Bye Bye
  condition: True
  timeout: 1

write_files:
  - path: /etc/docker/daemon.json
    content: |
      {
        "storage-driver":"overlay2",
        "hosts":[
          "unix:///var/run/docker.sock"
        ]
      }
  - path: /etc/montreal/local_configuration.json
    content: |
      {
        "meta": {
          "architecture": "{ARCHITECTURE}",
          "device_id": "{DEVICE_ID}"
        },
        "location": {
          "building": "{BUILDING}",
          "room": "{ROOM}"
        },
        "sensors": {}
      }
