version: '3.3'

networks:
  traefik-net:
    external:
      name: traefik-net
  prometheus-net:
    external:
      name: prometheus-net

secrets:
  alertmanager.yml:
    external: true

services:
  alertmanager:
    image: prom/alertmanager:latest
    command:
      - '--config.file=/run/secrets/alertmanager.yml'
    secrets:
      - alertmanager.yml
    networks:
      prometheus-net:
      traefik-net:
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      placement:
        constraints:
          - node.role == manager
      labels:
        traefik.backend: alertmanager
        traefik.backend.loadbalancer.sticky: "true"
        traefik.docker.network: "traefik-net"
        traefik.enable: "true"
        traefik.frontend.entryPoints: "http"
        traefik.frontend.passHostHeader: "true"
        traefik.frontend.rule: "Host:alertmanager.{DOMAIN}"
        traefik.port: "9093"