version: '3.3'

networks:
  influxdb-net:
    external:
      name: influxdb-net
  traefik-net:
    external:
      name: traefik-net

services:
  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./var/lib/grafana:/var/lib/grafana
    networks:
      traefik-net:
      influxdb-net:
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      placement:
        constraints:
          - node.role == manager
      labels:
        traefik.backend: grafana
        traefik.backend.loadbalancer.sticky: "true"
        traefik.docker.network: "traefik-net"
        traefik.enable: "true"
        traefik.frontend.entryPoints: "http"
        traefik.frontend.passHostHeader: "true"
        traefik.frontend.rule: "Host:grafana.{DOMAIN}"
        traefik.port: "3000"
