version: '3.3'

networks:
  influxdb-net:
    external:
      name: influxdb-net
  nsq-net:
    external:
      name: nsq-net

secrets:
  montreal.json:
    external: true

services:
  influxdb_writer:
    image: "{IMAGE}-amd64"
    networks:
      influxdb-net:
      nsq-net:
    environment:
      CONFIG: /run/secrets/montreal.json
      SERVICE: "influxdb_writer"
    tty: true
    secrets:
      - montreal.json
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      placement:
        constraints:
          - node.role == manager
